version: '3.8'
services:

  canchu-app:
    image: zrlin/canchu
    container_name: canchu-app
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - canchu-redis
      - canchu-nginx
    env_file:
      - .env  # Use the .env file for environment variables
    networks:
      - canchu_network

  canchu-redis:
    container_name: canchu-redis
    image: redis:alpine
    networks:
      - canchu_network

  canchu-nginx:
    container_name: canchu-nginx
    image: nginx:mainline-alpine-slim
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ${NGINX_CERT_PATH}:/etc/nginx/cert.crt
      - ${NGINX_KEY_PATH}:/etc/nginx/cert.key
    networks:
      - canchu_network

networks:
  canchu_network:
